### ISSUE TITLE
Option to toggle per door type

### ISSUE THREAD

**Issue by Novaenia** [Phoupraw/ClientAutomaticDoors#1]
I just ran over this bridge and Client Automatic Doors tried to open the trapdoors. there doesn't seem to be a way to disable the mod specifically for those
![image](https://github.com/user-attachments/assets/91556704-169a-47ac-905f-688f6345a49f)

**Comment by Phoupraw** [comment]
This behavior shouldn't obstruct your motion. Though, I am thinking how to make it not to open a door if player can step on the door.
